Перевод архивных записей, создателя оповещений и админского факса
FlacoFF/FIJ_Foundation-19 pull request #54
Opened 2022-10-01 19:15 UTC by FeudeyTF

## About the Pull Request

Поменял все английские тексты про SCP в архиве на их русские варианты, взятые с сайта https://scpfoundation.net
Перевёл "создателя" анонсов (Приоритетное оповещение, оповещение службы безопасности и оповещение совета О5)
Перевёл футер административного факса, который могут посылать админы

## Why It's Good For The Game

Перевод на русский

## Changelog

:cl:
code: перевод
/:cl:

2022-10-07 20:28 UTC, Mihail-Zub commented
по хорошему всё таки изменить само значение [GLOB.using_map.boss_name] а не заменять его.
везде где написано про зоны заменить на нашу "Зона 53"(именно то где сказано что объект хранится в зоне).
В документе о SCP-096 убрать последний абзац про уничтожение объекта.

Было бы хорошо всем кетерам сделать красный цвет(скрин 1)
также то что на остальных скриншотах
![image](https://user-images.githubusercontent.com/80586098/194646726-dee0ade2-1170-49e2-b9e7-059bf5d481e6.png)
![image](https://user-images.githubusercontent.com/80586098/194647262-ec0b49d0-bce2-4a44-b266-688a312ba326.png)

2022-10-07 20:35 UTC, FeudeyTF commented
> (ну и конечно исправить Run Tests/Code ошибки)
Скорее всего происходят из-за символов " в середине текста, но в игре ни на что не влияет, исправлю

2022-10-07 20:41 UTC, Mihail-Zub commented
я посмотрел прошлые пуллы переводов,там ран тест на код тоже непрошёл.
так что если не исправишь думаю ничего такого не будет.

2022-10-07 21:46 UTC, FlacoFF requested changes
Стоит лучше писать O5 на латинице, а не кириллице.
Стоит лучше изменить и подогнать [GLOB.using_map.boss_name] под перевод, а не стирать его везде.
Ошибки в словах также присутствуют.

2022-10-08 08:44 UTC, FeudeyTF commented
> Стоит лучше писать `O5` на латинице, а не кириллице. Стоит лучше изменить и подогнать `[GLOB.using_map.boss_name]` под перевод, а не стирать его везде. Ошибки в словах также присутствуют. Остальные ошибки указали выше.
Изменил везде, где `Оповещение Совета О5` на Оповещение `[GLOB.using_map.boss_name]`, значение переменной boss_name находится в [site53_define.dm](https://github.com/FeudeyTF/FIJ_Foundation-19/blob/dev/maps/site53/site53_define.dm), не знаю, как сюда залить. 
Также исправил в файле с данными архива номера зон

2022-11-08 14:35 UTC, closed without merging